# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "base_java_vagrant"
  config.vm.hostname = "apacheartemis.vagrant.local"

  # Name the vagrant image
  config.vm.define :apacheartemis do |t|
  end

  # Create a private network, which allows host-only access to the machine
  config.vm.network :private_network, ip: "192.168.32.4"
  config.vm.network "public_network", ip: "192.168.64.4"

   # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine.
  config.vm.network "forwarded_port", guest: 8161, host: 8261, protocol: 'tcp'
  config.vm.network "forwarded_port", guest: 61616, host: 61616, protocol: 'tcp'

  # Add the Fuse files
  config.vm.provision "file", source: "/Users/garethah/Documents/redhat/jboss-amq/apache-artemis-1.0.0-bin.zip", destination: "/tmp/apache-artemis-1.0.0-bin.zip"
  config.vm.provision "file", source: "bootstrap-artemis.sh", destination: "/home/vagrant/bootstrap-artemis.sh"

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision :shell, path: "bootstrap.sh", privileged: false

  config.vm.post_up_message = "todo..."
end
