# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk
export JAVA_HOME

# User specific environment and startup programs
PATH=$PATH:$HOME/.local/bin:$HOME/bin:$JAVA_HOME/bin

export PATH
