# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.8.0"

# Install required Vagrant plugins
missing_plugins_installed = false
required_plugins = %w(vagrant-vbguest vagrant-hostmanager vagrant-cachier vagrant-triggers vagrant-auto_network)

required_plugins.each do |plugin|
  if !Vagrant.has_plugin? plugin
    system "vagrant plugin install #{plugin}"
    missing_plugins_installed = true
  end
end

# If any plugins were missing and have been installed, re-run vagrant
if missing_plugins_installed
  exec "vagrant #{ARGV.join(" ")}"
end

AutoNetwork.default_pool = '10.20.5.11/24'

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "jboss_eap_64"

  # Hashicorp atlas push
  config.push.define "atlas" do |push|
    push.app = "garethahealy/jboss_brms_62"
  end

  # Config /etc/hosts via plugin
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true

  # JON Server
  config.vm.define "brmsserver" do |brmsserver|
    # Assign network config
    brmsserver.vm.hostname = "jonserver.jbosson33.vagrant.local"
    brmsserver.vm.network "private_network", ip: "10.20.5.11"

    # Add the JBoss BRMS zip
    brmsserver.vm.provision "file", source: "~/.m2/repository/org/jboss/eap/brms-deployable-eap6/6.2.0.GA/brms-deployable-eap6-6.2.0.GA-eap6.zip", destination: "/opt/rh/brms-deployable-eap6-6.2.0.GA-eap6.zip"

    # Enable provisioning with a shell script. Additional provisioners such as
    # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
    # documentation for more information about their specific syntax and use.
    brmsserver.vm.provision :shell, path: "bootstrap.sh", privileged: false
  end
end
