# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.8.0"

# Install required Vagrant plugins
missing_plugins_installed = false
required_plugins = %w(vagrant-vbguest vagrant-hostmanager vagrant-cachier vagrant-triggers vagrant-auto_network)

required_plugins.each do |plugin|
  if !Vagrant.has_plugin? plugin
    system "vagrant plugin install #{plugin}"
    missing_plugins_installed = true
  end
end

# If any plugins were missing and have been installed, re-run vagrant
if missing_plugins_installed
  exec "vagrant #{ARGV.join(" ")}"
end

AutoNetwork.default_pool = '10.20.1.31/24'

require 'socket'
def private_ipv4
  Socket.ip_address_list.detect{|intf| intf.ipv4_private?}
end

hostmanager_ip = private_ipv4.ip_address unless private_ipv4.nil?

$setHostmanagerIp = <<SCRIPT
echo "#{hostmanager_ip}      hostmanager-vagrant.local" >> /etc/hosts
SCRIPT

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "puppetlabs/centos-7.0-64-puppet"
  config.vm.box_version = "= 1.0.5"

  # Hashicorp atlas push
  config.push.define "atlas" do |push|
    push.app = "garethahealy/jboss_fuse_621_puppet_child"
  end

  # Config /etc/hosts via plugin
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true

  # Fabric (i.e.: root controller node)
  config.vm.define "puppetchild" do |puppetchild|
    # Assign network config
    puppetchild.vm.hostname = "puppetchild.jbossfuse621.vagrant.local"
    puppetchild.vm.network "private_network", ip: "10.20.1.31"

    # Puppet module @ https://github.com/garethahealy/puppet
    puppetchild.vm.synced_folder "/Users/garethah/Documents/github/garethahealy/puppet", "/opt/garethahealy/puppet/modules"

    # Enable provisioning with a shell script. Additional provisioners such as
    # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
    # documentation for more information about their specific syntax and use.
    puppetchild.vm.provision :shell, inline: $setHostmanagerIp, privileged: true
    puppetchild.vm.provision :shell, path: "bootstrap.sh", privileged: false
  end
end
